name: mate_player
description: "Audio Player"
version: 1.2.0+4

environment:
  sdk: ^3.9.2
  flutter: 3.35.5

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2
  go_router: ^16.0.0
  provider: ^6.1.5
  audioplayers: ^6.5.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  drift: ^2.27.0
  drift_flutter: ^0.2.4
  shared_preferences: ^2.5.3
  json_serializable: ^6.9.5
  audio_metadata_reader: ^1.4.2
  gap: ^3.0.1
  lottie: ^3.3.1
  file_picker: ^10.2.0
  audio_service: ^0.18.18
  path_provider: ^2.1.5
  dynamic_color: ^1.7.0
  skeletonizer: ^2.1.0+1
  worker_manager: ^7.2.6
  permission_handler: ^12.0.1
  flutter_svg: ^2.2.0
  path: ^1.9.1
  json_annotation: ^4.9.0
  async: ^2.13.0
  url_launcher: ^6.3.1
  package_info_plus: ^8.3.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  window_manager: ^0.5.1
  crypto: ^3.0.6
  file_selector: ^1.0.3

dependency_overrides:
  archive: ^3.6.1

dev_dependencies:
  drift_dev: ^2.27.0
  build_runner: ^2.5.4

  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/logo/
