display_name: Mate Player

icon: assets/logo/logo_128.png

keywords:
  - Player
  - Mate
  - Music
  - Audio
  - Sound 
  - Playback

generic_name: Music Player


categories:
  - Music
  - Player
  - Audio


startup_notify: true

include: []