name: mateplayer 
base: core22
version: git 
summary: Simple Material music player
icon: snap/gui/mateplayer.png
description: |
  It is a local music player in a material design. 
  Add a folder with your audio files and start listening.

grade: stable 
confinement: strict 

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes

apps:
  mateplayer:
    command: mate_player
    extensions: [gnome] 
    slots:
      - dbus-mateplayer
    plugs:
      - audio-playback
      - home
      - desktop
      - desktop-launch
      - x11
      - wayland
      - opengl
    desktop: ${SNAP}/meta/gui/mateplayer.desktop

slots:
  dbus-mateplayer: 
    interface: dbus
    bus: session
    name: app.oss.mateplayer

parts:
  mateplayer:
    build-packages: [libgstreamer1.0-dev, libgstreamer-plugins-base1.0-dev]
    source: .
    plugin: flutter
    flutter-target: lib/main.dart

  zenity-integration:
    plugin: nil
    stage-snaps:
      - zenity-integration