name: mateplayer 
base: core22
version: git 
summary: Simple Material music player
icon: snap/gui/mateplayer.png
description: |
  It is a local music player in a material design. 
  Add a folder with your audio files and start listening.

grade: stable 
confinement: strict 

apps:
  mateplayer:
    command: mate_player
    common-id: app.oss.mateplayer
    extensions: [gnome] 
    slots:
      - dbus-mateplayer
    plugs:
      - audio-playback
      - home
      - desktop
      - desktop-launch
      - desktop-legacy
      - x11
      - wayland
      - opengl
      - pulseaudio
      - unity7


slots:
  dbus-mateplayer: 
    interface: dbus
    bus: session
    name: app.oss.mateplayer

parts:
  mateplayer:
    build-packages: [libgstreamer1.0-dev, libgstreamer-plugins-base1.0-dev, libgtk-3-dev]
    stage-packages: 
    - libpulse0
    - libgtk-3-0
    - libgdk-pixbuf-2.0-0
    - libpango-1.0-0
    - libcairo2
    - libharfbuzz0b
    - libatk1.0-0
    - libglib2.0-0
    - libepoxy0
    - libfontconfig1
    - libfreetype6
    - libpng16-16
    - libjpeg8
    - libtiff5
    - libx11-6
    - libx11-xcb1
    - libxcb1
    - libxcb-randr0
    - libxcb-xfixes0
    - libxkbcommon0
    - libwayland-client0
    - libwayland-cursor0
    - libwayland-egl1
    - libxext6
    - libxcursor1
    - libxdamage1
    - libxcomposite1
    - libxrandr2
    - libxinerama1
    - libxrender1
    - libpcre2-8-0
    - libsqlite3-0 
    source: .
    plugin: flutter
    flutter-target: lib/main.dart

