name: mateplayer 
base: core24
version: git 
summary: Simple Material music player
icon: snap/gui/mateplayer.png
description: |
  It is a local music player in a material design. 
  Add a folder with your audio files and start listening.

grade: stable 
confinement: strict 

apps:
  mateplayer:
    command: mate_player
    common-id: app.oss.mateplayer
    extensions: [gnome] 
    slots:
      - dbus-mateplayer
    plugs:
      - audio-playback
      - home
      - desktop
      - desktop-launch
      - desktop-legacy
      - x11
      - wayland
      - opengl
      - pulseaudio


slots:
  dbus-mateplayer: 
    interface: dbus
    bus: session
    name: app.oss.mateplayer

parts:
  mateplayer:
    build-packages: [libgstreamer1.0-dev, libgstreamer-plugins-base1.0-dev, libgtk-3-dev]
    stage-packages: [libgtk-3-0, ibus-gtk3, libpulse0]
    source: .
    plugin: flutter
    flutter-target: lib/main.dart

  gpu-2404:
    after: [mateplayer]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
      # Workaround for https://bugs.launchpad.net/snapd/+bug/2055273
      mkdir -p "${CRAFT_PRIME}/gpu-2404"
    prime:
      - bin/gpu-2404-wrapper
