name: build_linux
on:
  workflow_dispatch

jobs:
  build_appimage:
    name: Linux AppImage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      
      - name: update
        run: sudo apt-get update

      - name: Install libgtk3
        run: sudo apt-get install build-essential libgtk-3-dev

      - name: Install GStreamer 
        run: sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio

      - name: Install Flutter
        uses: subosito/flutter-action@v2.21.0
        with:
            channel: stable
            flutter-version-file: pubspec.yaml
      
      - name: Build Linux Bundle
        run: |
          flutter clean
          flutter pub get
          flutter build linux --release

      - name: Get linuxdeploy
        run: |
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage
        
      - name: Create AppDir directory, copy bundle files 
        run: |
          mkdir app.AppDir/     
          cp -r build/linux/x64/release/bundle/* app.AppDir/
          cp assets/logo/logo_256.png app.AppDir/mate_player.png

      - name: Create AppRun file
        run: |
          cat << "EOF" > app.AppDir/AppRun
          #!/bin/bash

          cd "$(dirname "$0")"
          export LD_LIBRARY_PATH="/usr/lib:/lib:"
          exec ./mate_player
          EOF
          chmod +x app.AppDir/AppRun
      
      - name: Create .desktop file
        run: |   
          cat << "EOF" > app.AppDir/mate_player.desktop
          [Desktop Entry]
          Name=Mate Player
          GenericName=Music Player
          Exec=mate_player
          Icon=mate_player
          Type=Application
          StartupNotify=true
          Categories=AudioVideo
          Keywords=Player;Mate;Music;Audio;Sound;Playback
          EOF

      - name: Create AppImage (linuxdeploy)
        run: |
          ./linuxdeploy-x86_64.AppImage \
            --appdir app.AppDir \
            --desktop-file app.AppDir/mate_player.desktop \
            --icon-file app.AppDir/mate_player.png \
            --output appimage
        env: 
          LDAI_UPDATE_INFORMATION: gh-releases-zsync|a1exander-iv|mateplayer|latest|Mate_Player-*x86_64.AppImage.zsync

      - name: Create Archive Bundle
        run: |
          mkdir archive/
          tar -cvzf linux_archive_bundle.tar.gz -C build/linux/x64/release/ ./bundle
          sudo mv linux_archive_bundle.tar.gz /archive
        
      - name: find AppImage
        shell: bash
        run: echo APPIMAGE_PATH=$(realpath $(find ./ -name "*.AppImage")) >> $GITHUB_ENV

      - name: find .zsync
        shell: bash
        run: echo ZSYNC_PATH=$(realpath $(find ./ -name "*.zsync")) >> $GITHUB_ENV
      
      - name: Upload .zsync
        uses: actions/upload-artifact@v4.6.2
        with:
          name: zsync
          path: ${{env.ZSYNC_PATH}}
          
      - name: Upload AppImage
        uses: actions/upload-artifact@v4.6.2
        with:
          name: AppImage
          path: ${{env.APPIMAGE_PATH}}

      - name: Upload Archive Bundle Linux
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Archive Bundle
          path: "archive/linux_archive_bundle.tar.gz"