name: build_linux
on:
  workflow_dispatch

jobs:
  build_appimage:
    name: Linux AppImage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      
      - name: Install libgtk3
        run: sudo apt-get install build-essential libgtk-3-dev

      - name: Install Flutter
        uses: subosito/flutter-action@v2.21.0
        with:
            channel: stable
            flutter-version-file: pubspec.yaml
        
      - name: Install AppImageTool
        run: |
          wget -O appimagetool "https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage" 
          chmod +x appimagetool 
          sudo mv appimagetool /usr/local/bin/

      - name: Install Fastforge
        run: dart pub global activate fastforge

      - name: Build linux appimage
        run: fastforge release
      
      - name: Create Archive Bundle
        run: |
          tar -cvzf linux_archive_bundle.tar.gz -C build/linux/x64/release/ ./bundle
          mv linux_archive_bundle.tar.gz dist

      - name: find AppImage
        shell: bash
        run: | 
          echo APPIMAGE_PATH=$(realpath $(find ./dist -name "*.AppImage")) >> $GITHUB_ENV
         
      - name: Upload AppImage
        uses: actions/upload-artifact@v4.6.2
        with:
          name: AppImage
          path: ${{env.APPIMAGE_PATH}}

      - name: Upload Archive Bundle Linux
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Archive Bundle
          path: "dist/linux_archive_bundle.tar.gz"